// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

// Next.js lädt .env.local — die Prisma-CLI muss sie explizit lesen.
// Ohne Override-Verhalten: bereits gesetzte Env-Variablen gewinnen.
config({ path: ".env.local" });
config();

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: process.env["POSTGRES_URL_NON_POOLING"] || process.env["POSTGRES_PRISMA_URL"] || process.env["DATABASE_URL"] || "postgresql://dummy:dummy@localhost:5432/dummy",
  },
});
